function ARIMA_fourRemainder13 = arima_four_11(fourRemainder)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (fourRemainder)
%
%Output: The model containing estimated parameters (ARIMA_fourRemainder13)
%
%Auto-generated by MATLAB (R2025a) and Econometrics Toolbox Version 25.1 on 05-Nov-2025 22:20:11
fourRemainder1 = fourRemainder(:,1);

%% Autoregressive Integrated Moving Average Model
%Estimate an ARIMA Model of fourRemainder1
ARIMA_fourRemainder13 = arima('Constant',NaN,'ARLags',1,'D',0,'MALags',1,'Distribution','Gaussian');
ARIMA_fourRemainder13 = estimate(ARIMA_fourRemainder13,fourRemainder1,'Display','off');
end