function ARIMA_quadRemainder1 = arima_quad_31(quadRemainder)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (quadRemainder)
%
%Output: The model containing estimated parameters (ARIMA_quadRemainder1)
%
%Auto-generated by MATLAB (R2025a) and Econometrics Toolbox Version 25.1 on 05-Nov-2025 22:00:01
quadRemainder1 = quadRemainder(:,1);

%% Autoregressive Integrated Moving Average Model
%Estimate an ARIMA Model of quadRemainder1
ARIMA_quadRemainder1 = arima('Constant',NaN,'ARLags',1:3,'D',0,'MALags',1,'Distribution','Gaussian');
ARIMA_quadRemainder1 = estimate(ARIMA_quadRemainder1,quadRemainder1,'Display','off');
end