function ARIMA_cubicRemainder1 = arima_cubic_10(cubicRemainder)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (cubicRemainder)
%
%Output: The model containing estimated parameters (ARIMA_cubicRemainder1)
%
%Auto-generated by MATLAB (R2025a) and Econometrics Toolbox Version 25.1 on 05-Nov-2025 22:09:06
cubicRemainder1 = cubicRemainder(:,1);

%% Autoregressive Integrated Moving Average Model
%Estimate an ARIMA Model of cubicRemainder1
ARIMA_cubicRemainder1 = arima('Constant',NaN,'ARLags',1,'D',0,'MALags',[],'Distribution','Gaussian');
ARIMA_cubicRemainder1 = estimate(ARIMA_cubicRemainder1,cubicRemainder1,'Display','off');
end