function ARIMA_quadRemainder12 = arima_quad_10(quadRemainder)
%%Time Series Modeling Using the Econometric Modeler
% This code recreates the estimated model produced in the Econometric Modeler app. Use the code below to estimate the same model, or estimate a model with the same parameters on a new set of data.
%
%Input: A numeric matrix with the same number of columns as the data imported into the app (quadRemainder)
%
%Output: The model containing estimated parameters (ARIMA_quadRemainder12)
%
%Auto-generated by MATLAB (R2025a) and Econometrics Toolbox Version 25.1 on 05-Nov-2025 22:01:06
quadRemainder1 = quadRemainder(:,1);

%% Autoregressive Integrated Moving Average Model
%Estimate an ARIMA Model of quadRemainder1
ARIMA_quadRemainder12 = arima('Constant',NaN,'ARLags',1,'D',0,'MALags',[],'Distribution','Gaussian');
ARIMA_quadRemainder12 = estimate(ARIMA_quadRemainder12,quadRemainder1,'Display','off');
end