function [fitresult, gof] = cubicModel(cubicComp)
%CREATEFIT(CUBICCOMP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: cubicComp from allComponents
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Nov-2025 22:23:44


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], cubicComp );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cubicComp', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'cubicComp', 'Interpreter', 'none' );
grid on


