function [fitresult, gof] = createQuinticFit(quinticTrendLog)
%CREATEFIT(QUINTICTRENDLOG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: quinticTrendLog from usaTrain
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Jan-2026 15:22:41


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], quinticTrendLog );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'quinticTrendLog', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'quinticTrendLog', 'Interpreter', 'none' );
grid on


